### ISSUE TITLE
RX Example

### ISSUE THREAD

**Issue by d3dx9** [makar853/nethackrf#2]
Hey, 

I'm pretty new with the HackRF and would love to learn how to understand the data I get delivered by the HackRF. At the moment, I took a Stream Reader but I don't know how to understand the data delivered.

You might can give an example what do to with the data?

**Comment by makar853** [comment]
Hackrf streams data captured from its IQ demodulator. The data from stream is interpolated IQ samples in signed byte format. For example, first byte you get from stream is a first I sample, second byte is a first Q sample, third byte is a second I sample etc. 
This project was made to be used in LabVIEW environment as .NET by itself is not the best framework for digital signal processing applications.  So, most of the signal processing examples are written in [LabVIEW language](https://forums.ni.com/t5/USRP-Software-Radio/Does-LabVIEW-support-HackRF/td-p/3264743) 
I planned to do some examples for .NET core 5, but I haven't got around to it yet.

**Comment by d3dx9** [comment]
`            
int SampleCount = 10000;
            var iStream = new MemoryStream();
            var qStream = new MemoryStream();

            var iWriter = new BinaryWriter(iStream);
            var qWriter = new BinaryWriter(qStream);

            for (int i = 0; i < SampleCount; i++)
            {
                byte[] iq = new byte[2];
                reader.Read(iq, 0, iq.Length);
                iWriter.Write(iq[0]);
                qWriter.Write(iq[1]);

            }

            var iComponent = new RawSourceWaveStream(iStream, new WaveFormat(16000, 16, 1));
            var qComponent = new RawSourceWaveStream(qStream, new WaveFormat(16000, 16, 1));

            var waveProvider = new MultiplexingWaveProvider(new IWaveProvider[] { iComponent, qComponent }, 2);

            WaveFileWriter.CreateWaveFile("test.wav", waveProvider);

            iComponent.Dispose();
            qComponent.Dispose();

            iWriter.Dispose();
            qWriter.Dispose();
`

So for example, I found a little bit code for an RTL-SDR, this would create an Wave File from the IQ data, or do I understand this wrong?

**Comment by makar853** [comment]
I haven't worked with NAudio but it looks fine to me. Accessing RX stream for getting only 2 elements at once can have some negative effect on CPU consumption, but I haven't tried it, maybe it's ok.
I have added an FM receiver example to the master branch. It's bulky and unoptimized, but seems to be working.

**Comment by d3dx9** [comment]
Hi!

Thank you very much for the example. You might can tell me, where I can find how these filter work? Especially what the coefficients mean?

**Comment by makar853** [comment]
It's an equiripple FIR filter. https://www.recordingblogs.com/wiki/equiripple-filter . In general, you can calculate coefficients for FIR filters by performing an inverse FFT on the desired frequency response table. Or you can use one of already calculated filters such as equiripple or Kaiser-window filter and calculate coefficients using some formulas. Or make your own filter using Remez algorithm.

**Comment by d3dx9** [comment]
So how would you for example generate the Coefficients for a sample rate for 1.2Mhz in that example? I got already audio live played, but for that I need a less comsuption using decimation. 

I know, that I need a faktor of 25 for that sample rate but sadly (when I take the function from the hackrf.js example lowPassTaps) I get different results.

**Comment by makar853** [comment]
`static double[] coefs = {-0.000863, 	-0.000640, 	0.000513, 	0.003171, 	0.006720, 	0.009316, 	0.008373, 	0.001870, 	-0.009968, 	-0.023509, 	-0.031961, 	-0.027398, 	-0.004050, 	0.038474, 	0.093600, 	0.148922, 	0.189944, 	0.205088, 	0.189944, 	0.148922, 	0.093600, 	0.038474, 	-0.004050, 	-0.027398, 	-0.031961, 	-0.023509, 	-0.009968, 	0.001870, 	0.008373, 	0.009316, 	0.006720, 	0.003171, 	0.000513, 	-0.000640, 	-0.000863 };`

Fs=1,2MHz, Fpass=80kHz, Fstop=180kHz, Attenuation=60dB.

**Comment by d3dx9** [comment]
You might have an email address where I can send you my project? I have translated some hackrf.js functions and don't really understand it, if you want. You don't have to :D

**Comment by makar853** [comment]
You may upload it to dropbox or onedrive. I'll see what I can do, but no promises.
