### ISSUE TITLE
Unable to load DLL 'hackrf.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

### ISSUE THREAD

**Issue by ztamas83** [makar853/nethackrf#3]
Hi! I have spent several hours trying to figure out the source of the problem but I believe I need to ask for some help.
I have an application using HackRF and it works nicely on any dev computer. Now I deployed the app via an installer to the target machine (no Visual Studio installation!) and get the following exception:

```
System.TypeInitializationException: The type initializer for 'nethackrf.NetHackrf' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'hackrf.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at nethackrf.libhackrf.hackrf_init()
   at nethackrf.NetHackrf..cctor()
   --- End of inner exception stack trace ---
   at nethackrf.NetHackrf.HackrfDeviceList()
   at ***
   at ***
   at ***
```

As far as I'm concerned the DLL is in the same folder as the executable and the NetHackRf.dll:
![image](https://user-images.githubusercontent.com/71548739/230094238-922254b8-576b-4919-8de5-ed1b8ec6d814.png)

My last suspicion is that the hackrf.dll packaged with the NetHackRf is built in debug mode somehow and it requires additional SDKs or runtimes on the target machine. Is this a valid suspicion? Can someone confirm or just try to help me in any other way to get my app running on the target?

**Comment by makar853** [comment]
Hi. I checked x64 version of hackrf.dll with the dependency walker. I think that the only thing your computer can miss is vcruntime140.dll. Try to install Microsoft visual c++ redistributable 2015 or later version 
![Untitled](https://user-images.githubusercontent.com/57943827/230103240-e0f6580c-21c5-49a9-ab05-c5362a8f30b6.png)
P.S.: also make sure that all DLLs and your application are the same bitness.

**Comment by makar853** [comment]
Completely forgot about one more thing: before all of that above open properties of hackrf.dll and check that it's not blocked by windows. If so, click "unblock" button.
![Untitled (1)](https://user-images.githubusercontent.com/57943827/230111204-a93d8587-223d-4dc6-abf2-eafbab0bd6ca.png)

**Comment by ztamas83** [comment]
I installed the latest C++ redist package earlier today but no luck. I also checked with Dependency Walker earlier but must have missed some details. The MSVCR100.dll under PTHREADVC2.DLL is actually missing on the target. It's part of the VC++ redist 2012 version according to this:
https://answers.microsoft.com/en-us/windows/forum/all/windows-11-missing-msvcr100dll-and-msvcp100dll/93737f62-db4c-4d9e-ab61-89d60dd52f05

I will get back with the results.

**Comment by ztamas83** [comment]
> I installed the latest C++ redist package earlier today but no luck. I also checked with Dependency Walker earlier but must have missed some details. The MSVCR100.dll under PTHREADVC2.DLL is actually missing on the target. It's part of the VC++ redist 2012 version according to this: https://answers.microsoft.com/en-us/windows/forum/all/windows-11-missing-msvcr100dll-and-msvcp100dll/93737f62-db4c-4d9e-ab61-89d60dd52f05
> 
> I will get back with the results.

Had to go back one version, VS C++ Redist 2010 is required:
https://www.microsoft.com/en-us/download/details.aspx?id=26999

Now the problem is solved.

**Comment by makar853** [comment]
> Had to go back one version, VS C++ Redist 2010 is required: https://www.microsoft.com/en-us/download/details.aspx?id=26999
> 
> Now the problem is solved.

Interesting, I always thought that more recent versions of vc++ include older ones.

**Comment by ztamas83** [comment]
Could be an issue on Windows 11?

**Comment by makar853** [comment]
> Could be an issue on Windows 11?

I've never tested it on windows 11.
After googling vc++ I discovered that all-in-one package from microsoft includes only 2015-2022 versions. So 2005 - 2013 can only be installed separately. I should mention that in readme file.
